"""empty message

Revision ID: 8b833f43ceb0
Revises: 6e5aee3ef79e
Create Date: 2023-09-02 00:43:56.706022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b833f43ceb0'
down_revision = '6e5aee3ef79e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_item', schema=None) as batch_op:
        batch_op.drop_column('final_price')

    # ### end Alembic commands ###
